Fixed info_teleport_destination heights
momentum-mod/BSPConversionLib pull request #40
Opened 2023-03-30 19:41 UTC by Mac-tf2

2023-03-30 20:03 UTC, Panzerhandschuh requested changes

2023-03-30 20:03 UTC, Panzerhandschuh commented on BSPConversionLib/Source/EntityConverter.cs
> +			float.TryParse(origin[2], out var z);
This should be `float.Parse` instead of you are expecting the value to always parse successfully.

2023-03-30 20:06 UTC, Mac-tf2 commented on BSPConversionLib/Source/EntityConverter.cs
> +			origin[2] = (z - 24).ToString(); // teleport destinations are 24 units higher than they should be
The actual info_teleport_destination works correctly in hammer, I tested it. It's just the change from a misc_teleporter_dest to an info_teleport_destination places it at the wrong height.

2023-03-30 20:14 UTC, Panzerhandschuh commented on BSPConversionLib/Source/EntityConverter.cs
> +			origin[2] = (z - 24).ToString(); // teleport destinations are 24 units higher than they should be
In that case, `SetTeleportOrigin` should only be called when converting `misc_teleporter_dest` on line 110.

2023-03-30 20:27 UTC, Panzerhandschuh commented on BSPConversionLib/Source/EntityConverter.cs
> +			origin[2] = (z - 24).ToString(); // teleport destinations are 24 units higher than they should be
I think you just have to add `if (target.Classname != "info_teleport_destination")` so that it doesn't run multiple times.

2023-03-31 15:03 UTC, Panzerhandschuh commented on BSPConversionLib/Source/EntityConverter.cs
> +			if (target.ClassName != "info_teleport_destination")
Lines 753-754 should be nested within the foreach loop:
```
foreach (var target in targets)
{
    if (target.ClassName != "info_teleport_destination")
        ConvertTeleportDestination(target);
}
```

2023-03-31 17:47 UTC, Panzerhandschuh commented on BSPConversionLib/Source/EntityConverter.cs
> +			var origin = teleDest["origin"].Split(' ');
You can use `teleDest.Origin` instead of manually parsing the string.

2023-03-31 20:08 UTC, merged